/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugaspbo6;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Safriya Murni
 */
public class Tampilan extends javax.swing.JFrame {

    public void peringatan(String pesan) {
        JOptionPane.showMessageDialog(rootPane, pesan);
    }
    ArrayList<Mahasiswa> dataMahasiswa;

//insert 
    private int masukkanData(Connection conn, String nim, String nama, String jenis_kelamin, String alamat, String semester) throws SQLException {
        PreparedStatement pst = conn.prepareStatement("INSERT INTO mahasiswa (nim, nama, jenis_kelamin, alamat, semester) VALUES(?, ?, ?, ?, ?)");
        pst.setString(1, nim);
        pst.setString(2, nama);
        pst.setString(3, jenis_kelamin);
        pst.setString(4, alamat);
        pst.setString(5, semester);
        return pst.executeUpdate();
    }
//update

    private int perbaruiData(Connection conn, String nim, String nama, String jenis_kelamin, String alamat, String semester) throws SQLException {
        PreparedStatement pst = conn.prepareStatement("UPDATE mahasiswa SET nama=?, jenis_kelamin=?, alamat=?,semester=? WHERE nim=?");
        pst.setString(1, nama);
        pst.setString(2, jenis_kelamin);
        pst.setString(3, alamat);
        pst.setString(4, semester);
        pst.setString(5, nim);
        return pst.executeUpdate();
    }
//delete

    private int hapusData(Connection conn, String nim) throws SQLException {
        PreparedStatement pst = conn.prepareStatement("DELETE FROM mahasiswa WHERE nim=?");
        pst.setString(1, nim);
        return pst.executeUpdate();
    }

    private void tampil(Connection conn) {
        dataMahasiswa.clear();
        try {
            String sql = "select * from mahasiswa";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                Mahasiswa data = new Mahasiswa();
                data.setNim(String.valueOf(rs.getObject(1)));
                data.setNama(String.valueOf(rs.getObject(2)));
                data.setJenis_kelamin(String.valueOf(rs.getObject(3)));
                data.setAlamat(String.valueOf(rs.getObject(4)));
                data.setSemester(String.valueOf(rs.getObject(5)));
                dataMahasiswa.add(data);
            }
            DefaultTableModel model = (DefaultTableModel) jTableRecord.getModel();
            model.setRowCount(0);
            for (Mahasiswa data : dataMahasiswa) {

                Object[] baris = new Object[5];
                baris[0] = data.getNim();
                baris[1] = data.getNama();
                baris[2] = data.getJenis_kelamin();
                baris[3] = data.getAlamat();
                baris[4] = data.getSemester();

                model.addRow(baris);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Tampilan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Creates new form Tampilan
     */
    public Tampilan() {
        try {
            dataMahasiswa = new ArrayList<>();
            initComponents();
            Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5433/mahasiswa", "postgres", "bismillah");
            tampil(conn);
        } catch (SQLException ex) {
            Logger.getLogger(Tampilan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNIM = new javax.swing.JLabel();
        jLabelNama = new javax.swing.JLabel();
        jLabelSemester = new javax.swing.JLabel();
        jLabelAlamat = new javax.swing.JLabel();
        jTextFieldNIM = new javax.swing.JTextField();
        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldSemester = new javax.swing.JTextField();
        jTextFieldAlamat = new javax.swing.JTextField();
        jButtonSimpan = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jLabelJenisKelamin = new javax.swing.JLabel();
        jTextFieldJenisKelamin = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRecord = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNIM.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabelNIM.setText("NIM");

        jLabelNama.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabelNama.setText("Nama ");

        jLabelSemester.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabelSemester.setText("Semester");

        jLabelAlamat.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabelAlamat.setText("Alamat");

        jTextFieldNIM.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jTextFieldNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNIMActionPerformed(evt);
            }
        });

        jTextFieldNama.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jTextFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaActionPerformed(evt);
            }
        });

        jTextFieldSemester.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jTextFieldSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSemesterActionPerformed(evt);
            }
        });

        jTextFieldAlamat.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jTextFieldAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAlamatActionPerformed(evt);
            }
        });

        jButtonSimpan.setText("Simpan");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });

        jLabelJenisKelamin.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabelJenisKelamin.setText("Jenis Kelamin");

        jTextFieldJenisKelamin.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jTextFieldJenisKelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldJenisKelaminActionPerformed(evt);
            }
        });

        jTableRecord.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jTableRecord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Jenis Kelamin", "Alamat", "Semester"
            }
        ));
        jTableRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRecordMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableRecord);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSemester, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNIM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNama)
                            .addComponent(jTextFieldSemester)
                            .addComponent(jTextFieldAlamat)
                            .addComponent(jTextFieldJenisKelamin)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTextFieldNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonSimpan)
                        .addGap(30, 30, 30)
                        .addComponent(jButtonUpdate)
                        .addGap(35, 35, 35)
                        .addComponent(jButtonHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelNIM)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jTextFieldNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelNama)
                            .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelJenisKelamin)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jTextFieldJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAlamat)
                            .addComponent(jTextFieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSemester))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSimpan)
                            .addComponent(jButtonUpdate)
                            .addComponent(jButtonHapus)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNIMActionPerformed

    private void jTextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaActionPerformed

    private void jTextFieldSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSemesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSemesterActionPerformed

    private void jTextFieldAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAlamatActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        // TODO add your handling code here:
        String nim = jTextFieldNIM.getText().trim();
        String nama = jTextFieldNama.getText();
        String jenis_kelamin = jTextFieldJenisKelamin.getText();
        String alamat = jTextFieldAlamat.getText();
        String semester = jTextFieldSemester.getText();
        if (!nim.isEmpty() && !nama.isEmpty() && !jenis_kelamin.isEmpty() && !alamat.isEmpty() && (!semester.isEmpty())) {

            try {
                // TODO add your handling code here:
                Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5433/mahasiswa", "postgres", "bismillah");
                int k = masukkanData(conn, nim, nama, jenis_kelamin, alamat, semester);
                if (k > 0) {
                    tampil(conn);
                    this.peringatan("Simpan Berhasil");
                } else {
                    this.peringatan("Simpan Gagal");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Tampilan.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            this.peringatan("Input Data Mahasiswa Gagal");
        }
        jTextFieldNIM.setText("");
        jTextFieldNama.setText("");
        jTextFieldJenisKelamin.setText("");
        jTextFieldAlamat.setText("");
        jTextFieldSemester.setText("");

    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        // TODO add your handling code here:
        String nim = jTextFieldNIM.getText().trim();

        if (!nim.isEmpty()) {
            try {
                Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5433/mahasiswa", "postgres", "bismillah");
                int k = hapusData(conn, nim);
                if (k > 0) {
                    tampil(conn);
                    this.peringatan("Hapus Data Berhasil");
                } else {
                    this.peringatan("Hapus Data Gagal");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Tampilan.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            this.peringatan("Masukkan NIM untuk menghapus data");
        }
        jTextFieldNIM.setText("");
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jTextFieldJenisKelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJenisKelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldJenisKelaminActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        String nim = jTextFieldNIM.getText().trim();
        String nama = jTextFieldNama.getText();
        String jenis_kelamin = jTextFieldJenisKelamin.getText();
        String alamat = jTextFieldAlamat.getText();
        String semester = jTextFieldSemester.getText();
        if (!nim.isEmpty() && !nama.isEmpty() && !jenis_kelamin.isEmpty() && !alamat.isEmpty() && (!semester.isEmpty())) {

            try {
                Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5433/mahasiswa", "postgres", "bismillah");
                int k = perbaruiData(conn, nim, nama, jenis_kelamin, alamat, semester);
                if (k > 0) {
                    tampil(conn);
                    this.peringatan("Perbarui Data Berhasil");
                } else {
                    this.peringatan("Perbarui Data Gagal");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Tampilan.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            this.peringatan("Input Data Dosen Gagal");
        }
        jTextFieldAlamat.setText("");
        jTextFieldNIM.setText("");
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jTableRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRecordMouseClicked
        // TODO add your handling code here:
        try {
            Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5433/mahasiswa", "postgres", "bismillah");
            int row = jTableRecord.getSelectedRow();
            String tabel_klik = (jTableRecord.getModel().getValueAt(row, 0).toString());
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM Mahasiswa WHERE nim='" + tabel_klik + "'");
            if (sql.next()) {
                String nim = sql.getString("nim");
                jTextFieldNIM.setText(nim);
                String nama = sql.getString("nama");
                jTextFieldNama.setText(nama);
                String jenisKelamin = sql.getString("jenis_kelamin");
                jTextFieldJenisKelamin.setText(jenisKelamin);
                String alamat = sql.getString("alamat");
                jTextFieldAlamat.setText(alamat);
                String semester = sql.getString("semester");
                jTextFieldSemester.setText(semester);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTableRecordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Tampilan().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabelAlamat;
    private javax.swing.JLabel jLabelJenisKelamin;
    private javax.swing.JLabel jLabelNIM;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelSemester;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRecord;
    private javax.swing.JTextField jTextFieldAlamat;
    private javax.swing.JTextField jTextFieldJenisKelamin;
    private javax.swing.JTextField jTextFieldNIM;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldSemester;
    // End of variables declaration//GEN-END:variables
}
